name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  bump_version_tag:
    name: Bump version and push tag
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.create_tag.outputs.new_tag }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Execute action anothrNick/github-tag-action
      id: create_tag
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
  build:
    needs: bump_version_tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
      
    - name: Publish and zip
      run: |
          mkdir publish 
          dotnet publish SpriteCombiner/SpriteCombiner.csproj -c Release -r win-x64 --no-restore -p:PublishReadyToRun=false -p:PublishSingleFile=true --self-contained true -o publish/headless
          cp README.md publish 
          cd publish
          zip -r SpriteCombiner *
          mv SpriteCombiner.zip ../
    - name: Upload archive as release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GH_PACKAGES_TOKEN }}
        tag: ${{needs.bump_version_tag.outputs.new_tag}}
        artifacts: 'SpriteCombiner.zip'
        prerelease: false
